# Generated by Django 5.1.5 on 2025-01-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='genre_description',
            new_name='character_description',
        ),
    ]
